FROM node:20-alpine

WORKDIR /app

COPY backend/shared/ /app/shared/
COPY backend/gateway/package*.json /app/gateway/
WORKDIR /app/gateway
RUN npm install

COPY backend/gateway/ /app/gateway/

EXPOSE 3000

CMD ["node", "server.js"]
