FROM node:20-alpine

WORKDIR /app

COPY shared/ /app/shared/
COPY gateway/package*.json /app/gateway/
WORKDIR /app/gateway
RUN npm install

COPY gateway/ /app/gateway/

EXPOSE 3000

CMD ["node", "server.js"]
