FROM node:20-alpine AS build

WORKDIR /app

COPY frontend/dashboard/package*.json /app/
RUN npm install

COPY frontend/dashboard/ /app/
RUN npm run build

FROM nginx:alpine
COPY --from=build /app/build /usr/share/nginx/html
COPY frontend/dashboard/nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 3001

CMD ["nginx", "-g", "daemon off;"]
